# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports: 
      - 6379:6379

  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports: 
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - 8080:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
  catalogapi:
    container_name: catalogapi
    ports:
      - 8000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings:DatabaseName=ProductDb"
      - "DatabaseSettings:CollectionName=Products"
    depends_on:
      - catalogdb
  basketapi:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - 8001:5001
